### ISSUE TITLE
Example app fails to start

### ISSUE THREAD

**Issue by chazsconi** [derekkraan/horde#74]
Starting a single node with
`iex --name count1@127.0.0.1 --cookie asdf -S mix`

This is using current master and Elixir 1.7.4 and Erlang 20.2.3

It results in the following:
```
18:21:04.398 [info]  Starting Horde.RegistryImpl with name HelloWorld.HelloRegistry
 
18:21:04.401 [error] Process HelloWorld.HelloRegistry.RegistryCrdt (#PID<0.515.0>) terminating
** (ErlangError) Erlang error: :timeout_value
    (stdlib) gen_server.erl:389: :gen_server.loop/7
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: DeltaCrdt.CausalCrdt.init/1
Ancestors: [HelloWorld.HelloRegistry.Supervisor, HelloWorld.Supervisor, #PID<0.508.0>]
Message Queue Length: 0
Messages: []
Links: [#PID<0.516.0>, #PID<0.517.0>, #PID<0.518.0>, #PID<0.510.0>]
Dictionary: [rand_seed: {%{bits: 58, jump: #Function<8.15449617/1 in :rand.mk_alg/1>, next: #Function<5.15449617/1 in :rand.mk_alg/1>, type: :exrop, uniform: #Function<6.15449617/1 in :rand.mk_alg/1>, uniform_n: #Function<7.15449617/2 in :rand.mk_alg/1>, weak_low_bits: 1}, [37638961097853609 | 49241742922068666]}]
Trapping Exits: true
Status: :running
Heap Size: 610
Stack Size: 27
Reductions: 394
```

Only by reverting to v 0.3.0 and forcing `delta_crdt` to 0.3.1 can I get the example to start.

**Comment by doug-co** [comment]
I ran into this same thing, which I believe is because the registry_members function in application.ex statically defines both nodes.  So some communication is timing out when one of them doesn't exist.

**Comment by derekkraan** [comment]
Hi, thanks for the bug report! I had been seeing this error periodically in my testing, but hadn't come across a good way to reproduce it myself.

The bug was due to a loop in the code:
1. monitor all nodes
2. a node goes down (or was never up)
3. remove that node from the list of nodes
4. an updated list of nodes comes in
5. monitor all nodes

This was causing way more (thousands+) updates to the members CRDT than necessary.

I have fixed the bug and confirmed locally that it's not happening anymore.

Thanks again for reporting!

Fixed in commit 6c33f9e30a14a5f5fe81f1486a974858db20d418

**Comment by chazsconi** [comment]
For me the problem still occurs, but a little later after starting:
```
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]


10:30:29.325 [info]  Child Logger.ErrorHandler of Supervisor Logger.Supervisor started
Pid: #PID<0.166.0>
Start Call: Logger.Watcher.start_link({:error_logger, Logger.ErrorHandler, {true, true, 500}})
Restart: :permanent
Shutdown: 5000
Type: :worker
 
10:30:29.325 [info]  Application logger started at :"count1@127.0.0.1"
 
10:30:29.327 [info]  Application jason started at :"count1@127.0.0.1"
 
10:30:29.328 [info]  Application libcluster started at :"count1@127.0.0.1"
 
10:30:29.330 [info]  Application delta_crdt started at :"count1@127.0.0.1"
 
10:30:29.331 [info]  Application xxhash started at :"count1@127.0.0.1"
 
10:30:29.331 [info]  Application horde started at :"count1@127.0.0.1"
 
10:30:29.351 [info]  Starting Horde.RegistryImpl with name HelloWorld.HelloRegistry
 
10:30:29.352 [info]  Child HelloWorld.HelloRegistry.MembersCrdt of Supervisor HelloWorld.HelloRegistry.Supervisor started
Pid: #PID<0.177.0>
Start Call: DeltaCrdt.start_link(DeltaCrdt.AWLWWMap, [crdt: DeltaCrdt.AWLWWMap, notify: {HelloWorld.HelloRegistry, :members_updated}, name: HelloWorld.HelloRegistry.MembersCrdt, sync_interval: 5, ship_interval: 5, ship_debounce: 1])
Restart: :permanent
Shutdown: 5000
Type: :worker
 
10:30:29.365 [error] Process HelloWorld.HelloRegistry.RegistryCrdt (#PID<0.181.0>) terminating
** (ErlangError) Erlang error: :timeout_value
    (stdlib) gen_server.erl:389: :gen_server.loop/7
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: DeltaCrdt.CausalCrdt.init/1
```

**Comment by derekkraan** [comment]
@chazsconi, I am using handle_continue in delta_crdt, which requires >= OTP 21. There is no way to specify that currently in the mix file, so I'm not 100% sure how to proceed.

Do you specifically need support for OTP 20? Or can you easily upgrade?

**Comment by chazsconi** [comment]
@derekkraan Thanks for the info.  No problem for me in using OTP 21 - it's working fine for me with this version.  Perhaps you should clearly mention that >= OTP 21 is required somewhere and even fail in `delta_crdt` with a fatal error if a lower version is used.

**Comment by derekkraan** [comment]
@chazsconi I am going to fix delta_crdt so that it also works with OTP 20. Seems like the right thing to do (and is a minor change actually)

**Comment by derekkraan** [comment]
Fixed in delta_crdt 0.4.1.

**Comment by chazsconi** [comment]
OK great.  Thanks!
